8
olfies/thinknetica_offical pull request #8
Opened 2023-03-11 23:03 UTC by olfies

2023-03-14 06:50 UTC, VidgarVii requested changes

2023-03-14 06:50 UTC, VidgarVii commented on 7/cargo_carriage.rb
> +end
лишний end

2023-03-14 06:50 UTC, VidgarVii commented on 8/cargo_carriage.rb
> +  def has_free_volume?(volume)
точно такой же метод у класса CargoCarriage.
Можно метод перенести в класс Carriage. И так же подумать что еще можно вынести и избавиться от дублирования кода

2023-03-14 06:50 UTC, VidgarVii commented on 8/passenger_carriage.rb
> +  def take_a_seat
у грузового вагона есть точно такоё же метод, только с другим названием. Потенциальное место отрефачить код и убрать дублирование

2023-03-14 06:50 UTC, VidgarVii commented on 7/main.rb
> +  end
длинный метод можно сильно укоротить используй when ... then ...

Используй рубокоп
По моему я уже писал про это?!

2023-03-14 06:50 UTC, VidgarVii commented on 7/main.rb
> +    num_st = gets.chomp.to_i
не сокращая названия переменных. Ни чего хорошего в этом нет. Только усложняет понимание кода

2023-03-14 06:50 UTC, VidgarVii commented on 8/main.rb
> +class Controller
стоит вынести этот класс в controller.rb а не прятать его в main.rv

2023-03-14 06:50 UTC, VidgarVii commented on 8/main.rb
> +    trains = lambda do |train|
тут lambda будет излишней сложностью, если этого не было в ТЗ

2023-03-17 06:54 UTC, abr2001 commented on 8/station.rb
> +    @trains = {
тут должен быть массив, а не хеш

2023-03-17 06:54 UTC, abr2001 commented on 8/train.rb
> +    @trains.values.flatten.each do |train|
по всем вагонам надо

2023-03-17 06:54 UTC, abr2001 commented on 8/train.rb
> +    block.call(train)
альтернативный способ, обычно его и используют
`yield(train)` при этом не нужно явно передавать блок
работает быстрее
https://stackoverflow.com/questions/1410160/ruby-proccall-vs-yield

2023-03-18 08:42 UTC, abr2001 commented on 8/station.rb
> +    @trains = [
сделайте одномерный массив, сейчас у вас непонятно что, и не массив и не хеш,

просто сделайте @trains = []

тип уже хранится внутри объекта поезд, не надо его выделять отдельно, это избыточность

2023-03-18 08:42 UTC, abr2001 commented on 8/train.rb
>    def train_in(block)
написать метод, который принимает блок и проходит по всем **вагонам** поезда (вагоны должны быть во внутреннем массиве), передавая каждый объект **вагона** в блок.

ВАГОН

и используйте yield для вызова блока, я писал уже, call на практике не используют, он медленный и неудобный

2023-03-20 08:12 UTC, abr2001 approved these changes

2023-03-20 08:12 UTC, abr2001 commented on 8/station.rb
> +    self
self то зачем тут?
вы тогда станцию вернёте, а для чего?

2023-03-26 15:58 UTC, merged